name: LightAntiGrief
author: 'Statuxia'
version: '${version}'
main: me.statuxia.lightantigrief.LightAntiGrief
api-version: '1.21'
depend: [CoreProtect]
folia-supported: true

permissions:
  lag.moder:
    description: "Server Moderator"

commands:
  tpworld:
    permission: lag.moder
    description: "Teleport for moderators"
  marktrusted:
    permission: lag.moder
    description: "Mark player as trusted"